<script lang="ts">
  import { onMount } from "svelte";
  import { env } from "$env/dynamic/public";

  // Types
  interface ProsConsResult {
    topic: string;
    perspective: string;
    pros: string[];
    cons: string[];
    generatedAt: string;
  }

  // State variables
  let topic = "";
  let perspective = "";
  let isLoading = false;
  let result: ProsConsResult | null = null;
  let error = "";
  let usageCount = 0;
  let dailyLimit = 5;

  // Check usage count from localStorage
  onMount(() => {
    const today = new Date().toDateString();
    const storedUsage = localStorage.getItem("proscons_usage");
    const storedDate = localStorage.getItem("proscons_date");

    if (storedDate === today && storedUsage) {
      usageCount = parseInt(storedUsage, 10);
    } else {
      // Reset count for new day
      localStorage.setItem("proscons_date", today);
      localStorage.setItem("proscons_usage", "0");
      usageCount = 0;
    }

    dailyLimit = parseInt(env.PUBLIC_FREE_TIER_DAILY_LIMIT || "5", 10);
  });

  // Generate pros and cons
  async function generateProsAndCons() {
    if (!topic.trim()) {
      error = "Please enter a topic";
      return;
    }

    if (usageCount >= dailyLimit) {
      error = `You've reached your daily limit of ${dailyLimit} generations. Upgrade to Pro for unlimited access!`;
      return;
    }

    isLoading = true;
    error = "";
    result = null;

    try {
      const response = await fetch("/.netlify/functions/generate-pros-cons", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          topic: topic.trim(),
          perspective: perspective.trim(),
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Failed to generate pros and cons");
      }

      if (data.success) {
        result = data.data;

        // Update usage count
        usageCount++;
        localStorage.setItem("proscons_usage", usageCount.toString());
      } else {
        throw new Error("Invalid response format");
      }
    } catch (err) {
      error =
        err instanceof Error ? err.message : "An unexpected error occurred";
    } finally {
      isLoading = false;
    }
  }

  // Clear results
  function clearResults() {
    result = null;
    error = "";
    topic = "";
    perspective = "";
  }

  // Copy to clipboard
  async function copyToClipboard() {
    if (!result) return;

    const text = `Pros and Cons: ${result.topic}
${result.perspective !== "general" ? `Perspective: ${result.perspective}` : ""}

PROS:
${result.pros.map((pro, i) => `${i + 1}. ${pro}`).join("\n")}

CONS:
${result.cons.map((con, i) => `${i + 1}. ${con}`).join("\n")}

Generated by ProsCons Generator`;

    try {
      await navigator.clipboard.writeText(text);
      // Show success feedback (you could add a toast notification here)
    } catch (err) {
      console.error("Failed to copy to clipboard:", err);
    }
  }
</script>

<svelte:head>
  <title>ProsCons Generator - AI-Powered Decision Making Tool</title>
  <meta
    name="description"
    content="Generate comprehensive pros and cons for any topic using AI. Make better decisions with balanced insights."
  />
</svelte:head>

<div
  class="min-h-screen bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50"
>
  <!-- Header -->
  <header class="bg-white shadow-sm border-b border-gray-100">
    <div class="max-w-4xl mx-auto px-4 py-6">
      <div class="flex items-center justify-between">
        <div>
          <h1 class="text-3xl font-bold text-gray-900">
            <span class="text-blue-600">Pros</span><span class="text-red-500"
              >Cons</span
            > Generator
          </h1>
          <p class="text-gray-600 mt-1">AI-powered decision making tool</p>
        </div>
        <div class="text-right">
          <div class="text-sm text-gray-500">Free Tier</div>
          <div class="text-xs text-gray-400">
            {usageCount}/{dailyLimit} generations today
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <main class="max-w-4xl mx-auto px-4 py-8">
    <!-- Input Form -->
    <div class="bg-white rounded-xl shadow-lg p-6 mb-8">
      <div class="space-y-6">
        <div>
          <label
            for="topic"
            class="block text-sm font-medium text-gray-700 mb-2"
          >
            What would you like to analyze?
          </label>
          <input
            id="topic"
            type="text"
            bind:value={topic}
            placeholder="e.g., 'switching to a vegan diet', 'buying an electric car', 'working from home'"
            class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors"
            disabled={isLoading}
          />
        </div>

        <div>
          <label
            for="perspective"
            class="block text-sm font-medium text-gray-700 mb-2"
          >
            Perspective (optional)
          </label>
          <input
            id="perspective"
            type="text"
            bind:value={perspective}
            placeholder="e.g., 'environmental', 'financial', 'health'"
            class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors"
            disabled={isLoading}
          />
        </div>

        <div class="flex gap-4">
          <button
            on:click={generateProsAndCons}
            disabled={isLoading || !topic.trim() || usageCount >= dailyLimit}
            class="flex-1 bg-blue-600 text-white py-3 px-6 rounded-lg font-medium hover:bg-blue-700 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors flex items-center justify-center gap-2"
          >
            {#if isLoading}
              <svg class="animate-spin h-5 w-5" viewBox="0 0 24 24">
                <circle
                  class="opacity-25"
                  cx="12"
                  cy="12"
                  r="10"
                  stroke="currentColor"
                  stroke-width="4"
                ></circle>
                <path
                  class="opacity-75"
                  fill="currentColor"
                  d="M4 12a8 8 0 018-8V0a12 12 0 00-12 12h4z"
                ></path>
              </svg>
              Generating...
            {:else}
              🤔 Generate Pros & Cons
            {/if}
          </button>

          {#if result}
            <button
              on:click={clearResults}
              class="px-6 py-3 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
            >
              Clear
            </button>
          {/if}
        </div>
      </div>
    </div>

    <!-- Error Message -->
    {#if error}
      <div class="bg-red-50 border border-red-200 rounded-lg p-4 mb-8">
        <div class="flex">
          <div class="text-red-400">
            <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
              <path
                fill-rule="evenodd"
                d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z"
                clip-rule="evenodd"
              />
            </svg>
          </div>
          <div class="ml-3">
            <p class="text-sm text-red-800">{error}</p>
          </div>
        </div>
      </div>
    {/if}

    <!-- Results -->
    {#if result}
      <div class="bg-white rounded-xl shadow-lg overflow-hidden">
        <!-- Results Header -->
        <div class="bg-gray-50 px-6 py-4 border-b border-gray-200">
          <div class="flex items-center justify-between">
            <div>
              <h2 class="text-xl font-semibold text-gray-900">
                {result.topic}
              </h2>
              {#if result.perspective !== "general"}
                <p class="text-sm text-gray-600">
                  From a {result.perspective} perspective
                </p>
              {/if}
            </div>
            <button
              on:click={copyToClipboard}
              class="px-4 py-2 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-2"
            >
              <svg
                class="h-4 w-4"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                ></path>
              </svg>
              Copy
            </button>
          </div>
        </div>

        <div class="grid md:grid-cols-2 gap-0">
          <!-- Pros -->
          <div class="p-6 border-r border-gray-200">
            <div class="flex items-center gap-2 mb-4">
              <div class="text-green-500">
                <svg
                  class="h-6 w-6"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                  ></path>
                </svg>
              </div>
              <h3 class="text-lg font-semibold text-green-700">Pros</h3>
            </div>
            <ul class="space-y-3">
              {#each result.pros as pro, index}
                <li class="flex items-start gap-3">
                  <span
                    class="flex-shrink-0 w-6 h-6 bg-green-100 text-green-700 rounded-full flex items-center justify-center text-sm font-medium"
                  >
                    {index + 1}
                  </span>
                  <span class="text-gray-700">{pro}</span>
                </li>
              {/each}
            </ul>
          </div>

          <!-- Cons -->
          <div class="p-6">
            <div class="flex items-center gap-2 mb-4">
              <div class="text-red-500">
                <svg
                  class="h-6 w-6"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"
                  ></path>
                </svg>
              </div>
              <h3 class="text-lg font-semibold text-red-700">Cons</h3>
            </div>
            <ul class="space-y-3">
              {#each result.cons as con, index}
                <li class="flex items-start gap-3">
                  <span
                    class="flex-shrink-0 w-6 h-6 bg-red-100 text-red-700 rounded-full flex items-center justify-center text-sm font-medium"
                  >
                    {index + 1}
                  </span>
                  <span class="text-gray-700">{con}</span>
                </li>
              {/each}
            </ul>
          </div>
        </div>

        <!-- Generated timestamp -->
        <div
          class="bg-gray-50 px-6 py-3 text-xs text-gray-500 border-t border-gray-200"
        >
          Generated on {new Date(result.generatedAt).toLocaleString()}
        </div>
      </div>
    {/if}

    <!-- Upgrade CTA -->
    {#if usageCount >= dailyLimit - 1}
      <div
        class="mt-8 bg-gradient-to-r from-purple-600 to-blue-600 rounded-xl text-white p-6"
      >
        <div class="text-center">
          <h3 class="text-xl font-semibold mb-2">Ready for more insights?</h3>
          <p class="text-purple-100 mb-4">
            Upgrade to Pro for unlimited generations, advanced perspectives, and
            premium features!
          </p>
          <button
            class="bg-white text-purple-600 px-6 py-2 rounded-lg font-medium hover:bg-gray-100 transition-colors"
          >
            Upgrade to Pro (Coming Soon)
          </button>
        </div>
      </div>
    {/if}
  </main>

  <!-- Footer -->
  <footer class="bg-white border-t border-gray-200 mt-16">
    <div class="max-w-4xl mx-auto px-4 py-8">
      <div class="text-center text-gray-500 text-sm">
        <p>© 2024 ProsCons Generator. Made with ❤️ using AI.</p>
        <p class="mt-2">
          Helping you make better decisions, one analysis at a time.
        </p>
      </div>
    </div>
  </footer>
</div>
